//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFindingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_stream
    {
        public business_stream()
        {
            this.company = new HashSet<company>();
            this.user_student = new HashSet<user_student>();
        }
    
        public int businessId { get; set; }
        public string businessName { get; set; }
    
        public virtual ICollection<company> company { get; set; }
        public virtual ICollection<user_student> user_student { get; set; }
    }
}
