//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFindingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_location
    {
        public job_location()
        {
            this.job_post = new HashSet<job_post>();
        }
    
        public int jobLocationId { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string streetAddress { get; set; }
    
        public virtual ICollection<job_post> job_post { get; set; }
    }
}
