//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFindingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_post
    {
        public job_post()
        {
            this.job_post_activity = new HashSet<job_post_activity>();
        }
    
        public int jobPostId { get; set; }
        public int jobTypeID { get; set; }
        public int companyID { get; set; }
        public string isCompanyNameHidden { get; set; }
        public System.DateTime postCreatedDate { get; set; }
        public System.DateTime postEndedDay { get; set; }
        public string jobDescription { get; set; }
        public int jobLocationID { get; set; }
        public string isActivePost { get; set; }
        public string jobPostTitle { get; set; }
        public string department { get; set; }
        public string experienceStatus { get; set; }
        public string educationInfo { get; set; }
        public string militaryStiation { get; set; }
    
        public virtual company company { get; set; }
        public virtual job_location job_location { get; set; }
        public virtual ICollection<job_post_activity> job_post_activity { get; set; }
        public virtual job_type job_type { get; set; }
    }
}
