//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobFindingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class languages
    {
        public languages()
        {
            this.user_language_skill = new HashSet<user_language_skill>();
        }
    
        public int languageId { get; set; }
        public string languageName { get; set; }
    
        public virtual ICollection<user_language_skill> user_language_skill { get; set; }
    }
}
